swagger: "2.0"
info:
    title: Authenticated Math Service
    description: API for numeric operations, protected by OAuth2
    version: ""
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /auth:
        post:
            tags:
                - token
            summary: auth token
            description: |-
                Accepts username and password in the body and returns JWT OAUTH2/OIDC token with the username as a subject, expiring in 1 hour.
                The username and password are not verified, but cannot be empty strings.
            operationId: token#auth
            produces:
                - application/json
            parameters:
                - name: AuthRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TokenAuthRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/TokenAuthMalformedPayloadResponseBody'
            schemes:
                - http
    /math/openapi.json:
        get:
            tags:
                - math
            summary: Download ../gen/http/math_openapi.json
            operationId: math#/math/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /math/openapi.yaml:
        get:
            tags:
                - math
            summary: Download ../gen/http/math_openapi.yaml
            operationId: math#/math/openapi.yaml
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /mul/{numbers}:
        get:
            tags:
                - math
            summary: mul math
            description: "Accepts a sequence of numbers and multiplies them.\nIf any of the arguments is not a valid number, it returns an error. \n\nProtected with a valid JWT token, generated by the /auth endpoint, provided as a Bearer Authorization header.\nThe response is the multiplication of all numbers."
            operationId: math#mul
            produces:
                - text/plain
            parameters:
                - name: numbers
                  in: path
                  description: The array of numbers to multiply
                  required: true
                  type: array
                  items:
                    type: string
                  collectionFormat: multi
                - name: Authorization
                  in: header
                  description: Auth token
                  required: true
                  type: string
                  pattern: ^Bearer [^ ]+$
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/MathMulMalformedPayloadResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/MathMulUnauthorizedResponseBody'
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /sum:
        post:
            tags:
                - math
            summary: sum math
            description: "Accepts an arbitrary document as payload and sums the numbers contained within.\nThe document can contain a variety of things: arrays [1,2,3,4], objects {\"a\":1, \"b\":2, \"c\":3}, numbers, and strings. \nThe endpoint should find all of the numbers throughout the document and add them together.\n\nFor example:\n* [1,2,3,4] and {\"a\":6,\"b\":4} both have a auth_sum of 10.\n* [[[2]]] and {\"a\":{\"b\":4},\"c\":-2} both have a auth_sum of 2.\n* {\"a\":[-1,1,\"dark\"]} and [-1,{\"a\":1, \"b\":\"light\"}] both have a auth_sum of 0.\n* [] and {} both have a auth_sum of 0.\n\nProtected with a valid JWT token, generated by the /auth endpoint, provided as a Bearer Authorization header.\nThe response is the sum of all numbers in the document."
            operationId: math#sum
            produces:
                - text/plain
            parameters:
                - name: Authorization
                  in: header
                  description: Auth token
                  required: true
                  type: string
                  pattern: ^Bearer [^ ]+$
                - name: string
                  in: body
                  description: The JSON document to sum the numbers contained within
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/MathSumMalformedPayloadResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/MathSumUnauthorizedResponseBody'
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /token/openapi.json:
        get:
            tags:
                - token
            summary: Download ../gen/http/token_openapi.json
            operationId: token#/token/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /token/openapi.yaml:
        get:
            tags:
                - token
            summary: Download ../gen/http/token_openapi.yaml
            operationId: token#/token/openapi.yaml
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    MathMulMalformedPayloadResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: mul_MalformedPayload_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    MathMulUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: mul_Unauthorized_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    MathSumMalformedPayloadResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: sum_MalformedPayload_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    MathSumUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: sum_Unauthorized_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenAuthMalformedPayloadResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: auth_MalformedPayload_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenAuthRequestBody:
        title: TokenAuthRequestBody
        type: object
        properties:
            password:
                type: string
                description: Password to access the service.
                example: password
            username:
                type: string
                description: Username to access the service.
                example: user
        example:
            password: password
            username: user
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: JWT-based authentication
        name: Authorization
        in: header
